### ISSUE TITLE
Instance for ()

### ISSUE THREAD

**Issue by Munksgaard** [esmolanka/sexp-grammar#11]
Would it make sense to add an instance for `()`? It could be `()` or `nil`.

**Comment by Munksgaard** [comment]
Also, it would be nice with instances for a few more tuples-lengths.

**Comment by esmolanka** [comment]
In practice I often end up not using the `SexpIso` class at all since the default `Bool` instance or `Maybe` instance is not what I want in that particular case. This is why I was even thinking of removing `SexpIso` class from the next major version. But if the class is useful, adding instances for tuples of length 0 to 9 makes a lot of sense. (Also, probably for many other types.)

**Comment by Munksgaard** [comment]
Aha, so you write custom isomorphisms for everything?

For the record, I've just started using sexp-grammar, but I'm trying to create an isomorphism for the intermediate representation language (IR) in Futhark. If you're interested, you can see my progress [here](https://github.com/diku-dk/futhark/compare/sexp). As you can see, I tend to use the the `SexpIso` class quite a lot, but perhaps there's a better way? To be honest, I haven't even completed my translation yet, so it's very likely that some issues come up once I start trying to translate some real Futhark programs.

**Comment by esmolanka** [comment]
I think, for some types it makes sense. For others it probably does not. It's like having a `Monoid` instance for `Int` -- you have to arbitrarily choose whether it is an additive monoid you're interested in, or maybe multiplicative, or perhaps even with bitwise OR operation and 0 as a neutral element. If there is (or should be) only one way of writing `SexpIso` than I would say, it makes sense to have the instance. If the instance seems arbitrary, I'd say it's better to keep bare functions.

One of the modules where I mostly use functions: [Sugared.hs](https://github.com/esmolanka/lambdaf/blob/master/src/Syntax/Sugared.hs#L344-L614)

**Comment by esmolanka** [comment]
Btw, since you're implementing a grammar for a pretty large AST, I'd love to hear some feedback on the user experience side of using the library. I know, this `match $ With ...` pattern can be pretty frustrating because it's positional. And also not having a proper vocabulary of stack manipulation combinators is also sometimes limiting (however it is rather easy to fix).

**Comment by Munksgaard** [comment]
Of course! I'll try to write up something, once I have a more complete grammar :+1:

**Comment by esmolanka** [comment]
Please give it a try. (See [756503b1](https://github.com/esmolanka/sexp-grammar/commit/756503b1d164108a8b8dc52d63d79d72986df8d0))

**Comment by Munksgaard** [comment]
> Please give it a try. (See [756503b1](https://github.com/esmolanka/sexp-grammar/commit/756503b1d164108a8b8dc52d63d79d72986df8d0))

Excellent! I'll take a look tomorrow :+1:

**Comment by Munksgaard** [comment]
> Please give it a try. (See [756503b1](https://github.com/esmolanka/sexp-grammar/commit/756503b1d164108a8b8dc52d63d79d72986df8d0))

That's perfect! I can get rid of a few orphan instances now...

**Comment by Munksgaard** [comment]
Could you release a new version with these changes included, or are thinking about doing that larger refactoring first? Also, I promise I'll get around to writing about my experience with sexp-grammar, but probably not until later this week.

**Comment by esmolanka** [comment]
Yes, that's a good idea. I'll probably release a minor version later today.

No worries about the experience write-up.
