### ISSUE TITLE
`invertible-grammar` archived?

### ISSUE THREAD

**Issue by mitchellwrosen** [esmolanka/sexp-grammar#29]
Hey! I noticed the `invertible-grammar` repo is archived. Does that mean this library will eventually shed its dependency? Thanks.

**Comment by esmolanka** [comment]
@mitchellwrosen the repository `invertible-grammar` is archived because I moved the library to the current repository: https://github.com/esmolanka/sexp-grammar/tree/master/invertible-grammar. The separation between the libraries is going to remain; `sexp-grammar` will continue depending on `invertible-grammar`. Sorry for the confusion.
